export const paymentStyle = {
  overflowTextWrap: {
    width: "100%",
    height: "8%",
    display: "flex",
    alignItems: "center",
    color: "white",
    fontSize: "20px",
    padding: "0 2%",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
    justifyContent: "center",
  },
  outerDiv: {
    backgroundColor: "#00111c",
    width: "50%",
    height: "100%",
    padding: "2%",
  },
  dateTransactionOuterDiv: {
    width: "100%",
    height: "8%",
    display: "flex",
    color: "white",
  },
  commonDateAndTrans: { width: "50%", fontSize: "18px" },
  breakupOuter: {
    color: "white",
    marginTop: "5%",
    display: "flex",
    alignItems: "center",
  },
  horizontalLine: {
    width: "80%",
    borderTop: "1px solid white",
    margin: "1vh 0",
  },
  totalOuter: {
    display: "flex",
    width: "80%",
    justifyContent: "space-between",
    fontWeight: "bold",
  },
  leftText: { minWidth: "40%", fontSize: "1rem" },
  rightValue: { minWidth: "40%", fontSize: "1rem" },
  middleSign: { minWidth: "5%", fontSize: "1rem" },
  imgDiv: {
    width: "100%",
    height: "35%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    marginTop: "2%",
  },
  addressWrap: {
    fontSize: "20px",
    display: "-webkit-box",
    WebkitLineClamp: 4,
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  addressOuter: {
    width: "100%",
    height: "12%",
    color: "white",
    display: "flex",
    marginTop:"5%"
  },
};
